### arrange()

In [1]:
import numpy as np

In [3]:
arr1 = np.arange(0,10)
print(arr1)
arr2= np.arange(10,25,2)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]
[10 12 14 16 18 20 22 24]


In [5]:
arr3= np.arange(1,10,3)
print(arr3)

[1 4 7]


In [16]:
arr4 = np.ones(5,dtype = np.int8)
print(arr4)

[1 1 1 1 1]


In [18]:
arr4 = np.zeros(5,dtype = np.int8)
print(arr4)

[0 0 0 0 0]


In [ ]:
n1 = np.array([11,22,33,44])
n2 = np.array([10,20,30,40])