# first commnent

## 2nd comment

### 3rd comment

#### 4th comment

In [9]:
import numpy as np
import pandas as pd

In [11]:
print("Good morning")

Good morning


In [13]:
num = 10
print(f"value of num = {num}")

value of num = 10


In [15]:
a = 30
b = 50
print(f"Addition = {a+b}")

Addition = 80


In [17]:
# def function2():
#     n_arr = np.array([11,22,33,44,55])
#     print(n_arr)
#     print(f"Datatype of n_arr = {type(n_arr)}")
# function2()

In [24]:
# def function4():
#     print(n_arr)
#     print(f"Datatype of arr = {type(n_arr)}")
#     print(f"Dtype of arr = {n_arr.dtype}")
#     print(f"Itemtype of arr = {n_arr.itemsize}")
#     print(f"size of arr = {n_arr.size}")
#     print(f"Dimnesion of arr = {n_arr.ndim}")
#     print(f"Nbytes of arr = {n_arr.nbytes}")
 
# function4()

## indexing in numpy

In [31]:
n1 = np.array([11,22,33,44,55,66,77,88])

#slicing example

print(n1[2:5])
print(n1[-5:-2])
print(n1[-8:5])

print(f"Dimensions of arr = {n1.ndim}")
print(f"shape of arr = {n1.shape}")

n1 = n1.reshape

[33 44 55]
[44 55 66]
[11 22 33 44 55]
Dimensions of arr = 1
shape of arr = (8,)
